// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJBQ3uoGbu_f9kmP0qMKYb6ZCSvJz5R-Q',
    appId: '1:390579676069:web:cdda493d704745e63bfe4c',
    messagingSenderId: '390579676069',
    projectId: 'englishapp-43e6d',
    authDomain: 'englishapp-43e6d.firebaseapp.com',
    storageBucket: 'englishapp-43e6d.firebasestorage.app',
    measurementId: 'G-B0W66Z67EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkMzV8hZXPlzZEs9opSyTkSgUtfcjU-Q',
    appId: '1:390579676069:android:bc65a117d6737d363bfe4c',
    messagingSenderId: '390579676069',
    projectId: 'englishapp-43e6d',
    storageBucket: 'englishapp-43e6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV87c_uwhJ-7i8EH1NUmkdxguZtDvp2dM',
    appId: '1:390579676069:ios:a33ba65a0d9a65f93bfe4c',
    messagingSenderId: '390579676069',
    projectId: 'englishapp-43e6d',
    storageBucket: 'englishapp-43e6d.firebasestorage.app',
    iosClientId: '390579676069-t5pppt4gnveqeirbrjj3qsamftp1vveu.apps.googleusercontent.com',
    iosBundleId: 'com.tady0857.englishapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV87c_uwhJ-7i8EH1NUmkdxguZtDvp2dM',
    appId: '1:390579676069:ios:6881af47b9a9709f3bfe4c',
    messagingSenderId: '390579676069',
    projectId: 'englishapp-43e6d',
    storageBucket: 'englishapp-43e6d.firebasestorage.app',
    iosClientId: '390579676069-frmpgtodff68gtjbcfpqqe0mke71vq5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJBQ3uoGbu_f9kmP0qMKYb6ZCSvJz5R-Q',
    appId: '1:390579676069:web:c6e1193a933993873bfe4c',
    messagingSenderId: '390579676069',
    projectId: 'englishapp-43e6d',
    authDomain: 'englishapp-43e6d.firebaseapp.com',
    storageBucket: 'englishapp-43e6d.firebasestorage.app',
    measurementId: 'G-KK9GBP3TLK',
  );
}
